# Generated by Django 3.1.3 on 2022-03-05 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('nationality', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=50)),
                ('biodata', models.TextField()),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Fresher', 'Fresher'), ('Experience', 'Experience'), ('Experience Plus', 'Experience Plus')], max_length=50, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='session/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', multiselectfield.db.fields.MultiSelectField(choices=[('remote', 'Remote'), ('Onsite', 'On site')], max_length=100)),
                ('approach', multiselectfield.db.fields.MultiSelectField(choices=[('web_development', 'Web Development'), ('web_design', 'Web Design'), ('graphich_design', 'Graphich Design'), ('seo', 'Search Engine Optimization'), ('digital_merketing', 'Degital Merketing'), ('apps_development', 'App Development'), ('programing', 'Programing'), ('game_development', 'Game Development')], max_length=100)),
                ('skill', multiselectfield.db.fields.MultiSelectField(choices=[('social_media_marketing', 'Social media marketing'), ('search_engine_optimization', 'Search Engine Optimization'), ('adobe_photoshop', 'Adobe Photoshop'), ('html', 'html'), ('css', 'css'), ('javascript', 'javascript'), ('wordpress', 'wordpress'), ('php', 'php'), ('python', 'python'), ('go', 'go'), ('java', 'java'), ('c++', 'c++')], max_length=100)),
                ('expected_salary', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('in_job', 'In Job')], max_length=100)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='jobpost.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
