# Generated by Django 3.1.3 on 2022-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_tuitionprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Fresher', 'Fresher'), ('Experience', 'Experience'), ('Experience Plus', 'Experience Plus')], max_length=50, null=True),
        ),
    ]
