# Generated by Django 3.1.3 on 2022-03-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20220304_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='medium',
            new_name='skill',
        ),
    ]
