# Generated by Django 3.1.3 on 2022-03-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20220304_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='days_per_week',
        ),
    ]
