# Generated by Django 3.1.3 on 2022-03-03 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_remove_jobprofile_days_per_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='salary',
            new_name='expected_salary',
        ),
    ]
