# Generated by Django 3.1.3 on 2022-03-03 21:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0013_auto_20220121_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='class_in',
        ),
        migrations.RemoveField(
            model_name='post',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
        migrations.AddField(
            model_name='post',
            name='Expertise',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('web_development', 'Web Development'), ('web_design', 'Web Design'), ('graphich_design', 'Graphich Design'), ('seo', 'Search Engine Optimization'), ('digital_merketing', 'Degital Merketing'), ('apps_development', 'App Development'), ('programing', 'Programing'), ('game_development', 'Game Development'), ('other', 'Other')], default='other', max_length=115),
        ),
        migrations.AddField(
            model_name='post',
            name='Skill',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('social_media_marketing', 'Social media marketing'), ('search_engine_optimization', 'Search Engine Optimization'), ('adobe_photoshop', 'Adobe Photoshop'), ('html', 'html'), ('css', 'css'), ('javascript', 'javascript'), ('wordpress', 'wordpress'), ('php', 'php'), ('python', 'python'), ('go', 'go'), ('java', 'java'), ('c++', 'c++'), ('other', 'Other')], default='other', max_length=124),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Student', 'Student'), ('Fresher', 'Fresher'), ('Experience', 'Experience'), ('Experience Plus', 'Experience Plus')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Class_in',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
